version: '2'

services:
  geoserver:
    image: tb4mmaggots/geoserver:2.8.5
    env_file: ./geoserver/ENV
    links:
      - geofence
      - postgis
    ports:
      - '8001:8080'
    volumes:
      - ./geoserver/data:/var/geoserver
      # - ./geoserver/server.xml:/usr/local/tomcat/conf/server.xml
  geofence:
    image: tb4mmaggots/geofence
    env_file: ./geofence/ENV
    ports:
      - '8002:8080'
    links:
      - postgis
    volumes:
      - ./geofence/geofence-datasource-ovr.properties:/usr/local/tomcat/webapps/geofence/WEB-INF/classes/geofence-datasource-ovr.properties
  postgis:
    image: cheewai/postgis
    # Refer to https://hub.docker.com/_/postgres/ for other possibilities
    env_file: ./postgis/ENV
    ports:
      - "5432:5432"

    volumes:
      # Mount your data directory so your database may be persisted
      - ./postgis/data:/var/lib/postgresql/data
      - ./postgis/runtime:/runtime/data
      #*** If you have no existing database, comment the following the first-run
      #*** Empty data directory triggers initdb to be run
      # Customize access control to overwrite the default
      #- path/to/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:ro
      # Customize server tuning parameters to overwrite the default
      #- path/to/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
